### ISSUE TITLE
Unable to proxy request to https enpoint with selfsigned certificate

### ISSUE THREAD

**Issue by pmajkutewicz** [jmartin82/mmock#25]
Any chances for help with that kind of error:
```
2017/02/28 16:15:24 http: panic serving 127.0.0.1:54820: Get https://path.abexample.net:44444/example/v1/test: x509: certificate is valid for *.ab*.net, not path.abexample.net
goroutine 67 [running]:
net/http.(*conn).serve.func1(0xc8202faa00)
	/usr/lib/go-1.6/src/net/http/server.go:1389 +0xc1
panic(0x8626c0, 0xc820325950)
	/usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
github.com/jmartin82/mmock/proxy.(*Proxy).MakeRequest(0xc8204db980, 0x0, 0x0, 0xc8203c477d, 0x3, 0xc8203c83e0, 0x11, 0x0, 0x0, 0x0, ...)
	/home/test/go_path/src/github.com/jmartin82/mmock/proxy/proxy.go:31 +0x528
github.com/jmartin82/mmock/server.(*Dispatcher).ServeHTTP(0xc82001e6c0, 0x7fd062a1e1e0, 0xc82001a1a0, 0xc820308460)
	/home/test/go_path/src/github.com/jmartin82/mmock/server/dispatcher.go:67 +0x55f
net/http.serverHandler.ServeHTTP(0xc820092680, 0x7fd062a1e1e0, 0xc82001a1a0, 0xc820308460)
	/usr/lib/go-1.6/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc8202faa00)
	/usr/lib/go-1.6/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/lib/go-1.6/src/net/http/server.go:2137 +0x44e
```
Is there a switch that i can use it to turn of certificate verification?

**Comment by jmartin82** [comment]
Fixed on #

**Comment by pmajkutewicz** [comment]
Thanks!
